### ISSUE TITLE
No server tests when practicalmeteor:mocha is added

### ISSUE THREAD

**Issue by trajano** [DispatchMe/meteor-mocha-phantomjs#10]
When `practicalmeteor:mocha` is added to the application, running `meteor test practicalmeteor:mocha` and then accessing http://localhost:3000/ will show that there are no server tests when there are some present.

**Comment by aldeed** [comment]
Known issue with practicalmeteor:mocha. See here: https://github.com/practicalmeteor/meteor-mocha/issues/23

[dispatch:mocha-browser](https://github.com/DispatchMe/meteor-mocha-browser) works as an alternative to `practicalmeteor:mocha`. Only difference is it displays server test results in the server console rather than in the browser.
