### ISSUE TITLE
There is no route for the path: /

### ISSUE THREAD

**Issue by Mokto** [DispatchMe/meteor-mocha-phantomjs#19]
Hi,

Everything works fine dispatch:mocha-browser, my tests are running without any trouble.

But when I try to implement continuous integration, I get this : 

QNetworkReplyImpl: backend error: caching was enabled after some bytes had been written.
There is no route for the path: /

![capture d ecran 2016-06-03 a 13 47 58](https://cloud.githubusercontent.com/assets/5103928/15787732/e5362986-2991-11e6-8053-3e339800022c.png)

Repo is here : https://github.com/inProgress-team/mantra-webpack-boilerplate.

Thanks !

**Comment by aldeed** [comment]
@Mokto what command are you using to run them? Are you running app tests or unit tests?

**Comment by Mokto** [comment]
I'm running `meteor test --driver-package=dispatch:mocha-phantomjs`

I'm running only unit tests ;)

**Comment by aslafy-z** [comment]
Did you manage to make it work ?

**Comment by tcastelli** [comment]
Also facing the same issue

**Comment by aldeed** [comment]
This error does appear most of the time, but it should not cause any problems. If client tests aren't running it would be for some other reason.

Closing since this repo is being replaced by the updated [dispatch:mocha](https://github.com/DispatchMe/meteor-mocha). Please repost in that repo if this is still an issue.
