### ISSUE TITLE
Process prematurely exiting

### ISSUE THREAD

**Issue by billyvg** [DispatchMe/meteor-mocha-phantomjs#36]
We are using v0.1.8 because we get the unterminated string problem with 0.1.9. After running tests we get this output:

```
I20161208-11:34:44.176(-8)?   585 passing (2m)
I20161208-11:34:44.176(-8)?   275 failing

.... list of failed tests + stack traces ....
```

But the list of failed tests stop at #12, and the process exits prematurely without an error code. This has caused our CI to incorrectly report our suite as passing when it has failures.

Also noticing a lot of these messages:
```
Received error from server:  Parse error
```

**Comment by jbbr** [comment]
I have probably the same problem. It seems to be because the phantomjs binary is fetched for the wrong architecture.

`meteor npm rebuild` does not help as it recompiles/fetches only the phantomjs-prebuild in `./node_modules/` but not the one used by this package in `./.meteor/packages/dispatch_phantomjs-tests/.0.0.7.qfbes++os+web.browser+web.cordova/npm/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs`

So this seems to be related to the 0.0.7 phantomjs upgrade in https://github.com/DispatchMe/meteor-phantomjs-tests and might be an upstream issue in the phantomjs-prebuilt npm package.
I'll investigate further

**Comment by aldeed** [comment]
If you can work with MDG to get the latest version of this pkg working for you, it may resolve this. That will get you on the latest version of phantomjs.

**Comment by aldeed** [comment]
Closing since this repo is being replaced by the updated [dispatch:mocha](https://github.com/DispatchMe/meteor-mocha). Please repost in that repo if this is still an issue.
